main:
  serialport: /dev/ttyUSB13
  destination: mqtt
  compare_previous_readings: true
  energy_threshold: 1
  volume_threshold: 3
    
mqtt:
  broker: 192.168.1.X
  port: 8883
  username: mqtt
  password: password
  certificate: /etc/ssl/certs/ca-certificates.crt
  tls_version: TLSv1_2
  tls_insecure: false
  topic: home-assistant/stadsverwarming
  retain: true
  